version: '3.0'
services:
  todoback:
    image: todobackend
    ports:
      - 3001:3001

  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - todobackend
    environment:
      - REACT_APP_API_HOST=todoback


  todotests:
    image: todotests
    depends_on:
      - todofrontend
      - todobackend
    environment:
      - FRONT_HOST=todofront
    
